services:
  db:
    container_name: db_postgres_fitness
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 8432
      POSTGRES_DB: postgres
    ports:
      - "8888:8432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  app:
    container_name: api_fast_api_fitness
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/8432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8080'
    ports:
      - 8889:8080
    restart: always
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge
